### ISSUE TITLE
Feature: random quote slash command

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode-pybot#12]
# Description

I'd love to be able to have a list of random quotes so I can have them post in the channel.

Maybe even include a fuzzy text search to find ones that match?

# Purpose

This would be interesting to get this.

**Comment by Mahafilac** [comment]
I love this Idea, how would I do a pull request to do this one 👍 💯

**Comment by mega-mac-slice** [comment]
@Mahafilac @wimo7083 Let's go through a few example use cases:
#### Case: Random Famous Quote
`/repeat quote`
<img width="685" alt="screen shot 2018-10-14 at 5 24 52 pm" src="https://user-images.githubusercontent.com/25651292/46923554-88ceb800-cfd6-11e8-9725-2b2fcd698213.png">
[builder](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22%60%60%60Any%20fool%20can%20know.%20The%20point%20is%20to%20understand.%60%60%60%20%E2%80%95%20_Albert%20Einstein_%22%7D)
#### Case: Random OC User Quote
`/repeat quote`
<img width="672" alt="screen shot 2018-10-14 at 5 30 53 pm" src="https://user-images.githubusercontent.com/25651292/46923597-08f51d80-cfd7-11e8-84c4-9371edf9ea2c.png">
[builder](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22%60%60%60Be%20nice.%20Or%20Else.%60%60%60%20%E2%80%95%20_Ashley_%22%7D)
#### Case: OC User Quote By Reference
`/repeat quote #be-nice`
<img width="672" alt="screen shot 2018-10-14 at 5 30 53 pm" src="https://user-images.githubusercontent.com/25651292/46923597-08f51d80-cfd7-11e8-84c4-9371edf9ea2c.png">
[builder](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22%60%60%60Be%20nice.%20Or%20Else.%60%60%60%20%E2%80%95%20_Ashley_%22%7D)

Case `OC User Quote By Reference` kind of touches on the `Maybe even include a fuzzy text search to find ones that match?` that @wimo7083 mentions, but instead of searching would just allow users to reference a specific quote by a shortened stub. Would that work for you @wimo7083?

@wimo7083 Assuming we wanted to manage these quotes in a yaml file of some kind (which I'm just suggesting based off the resources.yaml) where would you want this added to the repo?

**Comment by wimo7083** [comment]
Hey guys sorry, I wasn't getting any notifications in \#feed-github.

I don't want to dictate how you do this too much, if you want partial string matching [aka fuzzy](https://marcobonzanini.com/2015/02/25/fuzzy-string-matching-in-python/) go ahead. If you want specific examples that's also great too. 
I'd recommend you do this iteratively, start off with something simple and then progress to more advance.

As always ping me in slack if I don't respond quick enough.

**Comment by platipo** [comment]
Hi everyone, I would like to work on this if nobody is already doing it!

**Comment by aaron-suarez** [comment]
If anyone wants this functionality, feel free to open a PR. We do not feel like this is important enough to keep on the backlog when we start to ramp up development on this over the next few months.
